export const MESSAGE_HANDLER_METADATA = 'LAIKA::MESSAGE_HANDLER';

export const MESSAGE_HANDLER_PARAMS_METADATA = 'LAIKA::MESSAGE_HANDLER_PARAMS_METADATA';

export enum MessageHandlerParamsTypes {
  MESSAGE_TEXT = 'MESSAGE_TEXT',
  TRIM_ENTITY = 'TRIM_ENTITY',
};

export const CORE_MODULE_OPTIONS = 'CORE_MODULE_OPTIONS';
